name: Update Thunderstore page
on:
    release:
        types: [published]
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
        - name: Fetch Sources
          uses: actions/checkout@v4
          with:
            ref: ${{ github.event.release.tag_name }}
            fetch-depth: 0
            filter: tree:0

        - uses: dhkatz/thunderstore-publish@v1.0.1
          id: publish
          with:
            token: ${{ secrets.TS_TOKEN }}
            namespace: CementGB
            name: CementGB
            description: A general-purpose modding API for Gang Beasts.
            version: ${{ github.event.release.tag_name }}
            communities: Gang Beasts
            categories: mods

        - name: Output URL
          run: echo "Published Thunderstore package to ${{ steps.publish.outputs.url }}"